# For physics topics, use the specific subtopics, e.g. "Astrophysics"
topic: "Statistics"
# An empty list here will include all categories in a topic
# Use the natural language names of the topics, found here: https://arxiv.org
# Including more categories will result in more calls to the large language model
categories: []

# Relevance score threshold. abstracts that receive a score less than this from the large language model
# will have their papers filtered out.
#
# Must be within 1-10
threshold: 8

# A natural language statement that the large language model will use to judge which papers are relevant 
#
# For example:
#     "I am interested in complexity theory papers that establish upper bounds"
#     "gas chromatography, mass spectrometry"
#     "making lots of money"
#
# This can be empty, which just return a full list of papers with no judgement or filtering,
# in whatever order arXiv responds with.
interest: |
  1. I am interested in methodological papers that are explicitly concerned with the topic of health equity.
  2. I am particularly interested in papers concerned with fairness and equity in the context of genomic studies or clinical trials.
  3. I am also interested in papers introducing new statistical or machine learning methods to identify or mitigate health disparities.
